# Generated by Django 4.1.2 on 2022-10-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "レシピ", "verbose_name_plural": "レシピ"},
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
    ]
